### Ask for movies
POST http://localhost:8080/ask-for-movies
Content-Type: application/json
Accept: application/json

{
  "movieQuestion": "Find me all movies by Steven Spielberg"
}

### Test Vector Store connection
GET http://localhost:9091/api/v1/collections